### ISSUE TITLE
How to insert code blocks?

### ISSUE THREAD

**Issue by Slapbox** [GitbookIO/slate-edit-code#11]
What exactly do you have to do to insert a slate-edit-code block once this is installed and added as a plugin?

I assume it's not all blocks by default. If it is, tab behavior is not working properly (tab loses focus)

**Comment by SamyPesse** [comment]
The plugin doesn't handle insertion of code block, but only edition inside the code block.

It currently doesn't export transforms to insert a code block. In our application, we are doing a simple `state.transform().insertNode(...)`.

But the plugin should expose a `editCode.transforms.insertBlock('Some code')`.

**Comment by Slapbox** [comment]
Okay make sense. Sorry for the maybe silly questions, I'm new to Slate.

If I have my cursor in a block of type 'code' and the cursor is within a `<pre>` and `<code>` tags, should I be able to use tab then? That's where I am now. Sorry, maybe I'm overlooking some implementation point or maybe I'm just not well versed enough in Slate?

**Comment by Slapbox** [comment]
Ah nevermind I made sense of it all. Thanks very much for your great work and your quick response.

**Comment by oyeanuj** [comment]
@Slapbox How did you end up adding code with the plugin?

**Comment by Slapbox** [comment]
I'm not really sure what the issue I was having all this time ago was. It looks like I thought this plugin added an actual block type to your schema, which it doesn't. 

If you can provide some more details on your issue I'd be happy to help. Or ping me on Slack when you're on and if I'm around I can try to help in real time.
