### ISSUE TITLE
Prism highlighting does not update all lines when changing syntax

### ISSUE THREAD

**Issue by echenley** [GitbookIO/slate-edit-code#17]
This probably has something to do with the lines refactor: https://github.com/GitbookIO/slate-edit-code/pull/10. The more basic Slate code-highlighting example does not have this issue: http://slatejs.org/#/code-highlighting

### Steps to Reproduce

- open a document on gitbook.com
- make a code block with
```js
var line1;
var line2;
```
- change syntax to javascript, then to css
- only currently focused line is updated
- if you focus the beginning of the incorrectly highlighted line, it triggers prism to update it
- if you focus the end of the incorrectly highlighted line, it throws an error

**Comment by Soreine** [comment]
Fixed in https://github.com/GitbookIO/slate-prism/pull/5
