### ISSUE TITLE
All code ending up in a single line block

### ISSUE THREAD

**Issue by tommoor** [GitbookIO/slate-edit-code#32]
It seems like in the latest version `0.13.2` there are not multiple code line blocks created in the editor, all of the code is put on a single block (in this case my `lineType` option is set to `code-line`) with newline characters ignored:

```json
{
  "kind": "block",
  "type": "code",
  "isVoid": false,
  "data": {},
  "nodes": [
    {
      "kind": "block",
      "type": "code-line",
      "isVoid": false,
      "data": {},
      "nodes": [
        {
          "kind": "text",
          "leaves": [
            {
              "kind": "leaf",
              "text": "type\ndescription\nname\n\nonDocumentCreate(document, settings, actor) {\n\n}\n\nonDocumentDelete() {\n\n}\n\nonCollectionCreate() {\n\n}",
              "marks": []
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Soreine** [comment]
I can't reproduce it either running this package example (see https://github.com/GitbookIO/slate-edit-code/issues/33#issuecomment-354121709)

**Comment by Soreine** [comment]
What options are you passing to the `slate-edit-code` by the way ?

**Comment by tommoor** [comment]
Similar to the other issue - I was expecting this plugin to split the code block automatically into code-line children but it seems the expectation is that this is done outside the plugin.
