### ISSUE TITLE
Don't work in slate 0.37

### ISSUE THREAD

**Issue by linonetwo** [GitbookIO/slate-edit-code#45]
Don't work in local development, try to reproduce in an online environment but there is another bug.
https://stackblitz.com/edit/react-fh7kbo?file=index.js

**Comment by linonetwo** [comment]
<img width="392" alt="wx20180818-160922 2x" src="https://user-images.githubusercontent.com/3746270/44297262-1789c600-a301-11e8-9ed3-e0fc5b73d189.png">
I add border to code block, seems that "enter" will add a new code block instead of a code line.

**Comment by linonetwo** [comment]
@Soreine  @SamyPesse 
I've made it worked.
https://github.com/GitbookIO/slate-edit-code/pull/46

**Comment by Soreine** [comment]
Thanks a lot :)

**Comment by linonetwo** [comment]
Closing due to the close of PR https://github.com/GitbookIO/slate-edit-code/pull/46#issuecomment-422760482
I may publish another npm package likes `slate-code-block` or so from my forked version since it's Apache License 2.0?

**Comment by cdunn** [comment]
@linonetwo did you ever get around to publishing somewhere? just starting down the road of updating all the slate plugin forks. thanks!

**Comment by linonetwo** [comment]
@cdunn  I've published it as https://www.npmjs.com/package/slate-code-block.

Thought there are some breaking changes in slate 0.40, I will adapt to that soon.
