### ISSUE TITLE
How to do syntax highlighting?

### ISSUE THREAD

**Issue by fandy** [GitbookIO/slate-edit-code#49]
The docs don't make this clear, but if I used Prism.js markup to render the `code_block` block, will the indentation behavior work?

**Comment by Slapbox** [comment]
@fandy have you seen the `Slate-Prism` library? Keep in mind this library and `Slate-Prism` are no longer supported for use with the master branch of Slate.

**Comment by fandy** [comment]
Ah yes, I was confused at first because it wasn't well documented 😛
