### ISSUE TITLE
Not compatible with slate 0.15

### ISSUE THREAD

**Issue by thesunny** [GitbookIO/slate-edit-code#8]
Just a note that the current version is not compatible with slate 0.15. The library expects Slate 0.14.

In case it was just a versioning issue, I tried changing the peer dependencies but I got this error:

```
Uncaught TypeError: rule.match is not a function(…)
```

I haven't investigated too much. Just wanted to give you a heads up.

Sunny

**Comment by SamyPesse** [comment]
It should be good now. (We are using it with the latest slate).
